// team-data.jsx — Verified team dataset sourced from https://whitelabelresell.com/team/
// Extracted 2026-08-07. All names, roles, images and LinkedIn URLs verified against the live page.
// Members with no real LinkedIn (placeholder "#" or missing) have linkedin: null.

window.TEAM = [
  {
    name: "Christian Clark",
    role: "Founder",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/1697726084291.jpeg",
    linkedin: "https://www.linkedin.com/in/christian-clark-9a352b179/",
    alt: "Christian Clark — Founder",
    width: 562,
    height: 562,
  },
  {
    name: "Himanshu Raikwar",
    role: "Lead Digital Designer",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Himanshu-Raikwar-1024x1024.png",
    linkedin: "https://www.linkedin.com/in/himanshuraikwar/",
    alt: "Himanshu Raikwar — Lead Digital Designer",
    width: 1024,
    height: 1024,
  },
  {
    name: "Mohammad Muneeb",
    role: "Lead SEO Specialist",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Mohammad-Muneeb-1024x1024.png",
    linkedin: "https://www.linkedin.com/in/mohammad-muneeb-204418215/",
    alt: "Mohammad Muneeb — Lead SEO Specialist",
    width: 1024,
    height: 1024,
  },
  {
    name: "Anil Raikwar",
    role: "Analytics Engineer",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Anil-Raikwar.png",
    linkedin: "https://www.linkedin.com/in/anil-raikwar/",
    alt: "Anil Raikwar — Analytics Engineer",
    width: 651,
    height: 649,
  },
  {
    name: "Haider Ali",
    role: "SEO Specialist",
    image: "https://whitelabelresell.com/wp-content/uploads/elementor/thumbs/Haider-Ali-rqg7xs8a0bnqe844b332hjurrpz1a11ezafcq7nbb4.png",
    linkedin: "https://www.linkedin.com/in/haider-naeem-888378249/",
    alt: "Haider Ali — SEO Specialist",
    width: 1024,
    height: 1024,
  },
  {
    name: "Brandon Carroll",
    role: "Acquisition Specialist",
    image: "https://whitelabelresell.com/wp-content/uploads/elementor/thumbs/Brandon-Carroll-rqg7xs8a0bnqe844b332hjurrpz1a11ezafcq7nbb4.png",
    linkedin: null,
    alt: "Brandon Carroll — Acquisition Specialist",
    width: 1024,
    height: 1024,
  },
  {
    name: "Taofeek Abdulrauf",
    role: "Cloud Engineer",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Taofeek-Abdulrauf-1024x1024.png",
    linkedin: "https://www.linkedin.com/in/taofeek-abdulrauf-a95815226/",
    alt: "Taofeek Abdulrauf — Cloud Engineer",
    width: 1024,
    height: 1024,
  },
  {
    name: "Munir Nadayako",
    role: "Web Developer",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Munir-Nadayako-1024x1022.png",
    linkedin: null,
    alt: "Munir Nadayako — Web Developer",
    width: 1024,
    height: 1022,
  },
  {
    name: "Mcjethro Kalu",
    role: "Frontend Developer",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Mcjethro-Kalu-1.png",
    linkedin: "https://www.linkedin.com/in/mcjethro-kalu-96270a237/",
    alt: "Mcjethro Kalu — Frontend Developer",
    width: 732,
    height: 733,
  },
  {
    name: "Asad Ehsan",
    role: "Administrator",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Asad-Ehsan-1021x1024.png",
    linkedin: null,
    alt: "Asad Ehsan — Administrator",
    width: 1021,
    height: 1024,
  },
  {
    name: "Zubair Tayyib",
    role: "Jr UI/UX Designer",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Zubair-Muhammad-Tayyib.png",
    linkedin: null,
    alt: "Zubair Tayyib — Jr UI/UX Designer",
    width: 528,
    height: 530,
  },
  {
    name: "Sochima Chukwu",
    role: "Jr Web Developer",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Sochi-1024x1016.png",
    linkedin: "https://www.linkedin.com/in/sochukwuma-chukwu/",
    alt: "Sochima Chukwu — Jr Web Developer",
    width: 1024,
    height: 1016,
  },
  {
    name: "Nathaniel Duku",
    role: "Jr Client Success Manager",
    image: "https://whitelabelresell.com/wp-content/uploads/2025/01/Nathaniel-Abiodun-Duku-1019x1024.png",
    linkedin: null,
    alt: "Nathaniel Duku — Jr Client Success Manager",
    width: 1019,
    height: 1024,
  },
];
